simulation_parameters:
  start_date: 2021-07-01
  end_date: 2022-07-01
  frequencies:
    - "10T"
    - "30T"
    - "1H"
  daily_seasonality_options:
    - "no"
    - "exist"
  weekly_seasonality_options:
    - "exist"
    - "no"
  noise_levels:
    - "small"
    - "large"
    - "none"
  trend_levels:
    - "exist"
    - "no"
  cyclic_periods:
    - "exist"
    - "no"
  data_types: "multiplicative"  # Make sure this line is correctly indented
  outliers_percentage: [0.05, 0]
  missing_percentage: [0.05, 0]
