simulation_parameters:
  start_date: 2021-07-01
  end_date: 2022-07-01
  frequencies:
    - "10T"
    - "30T"
    - "1H"
  daily_seasonality_options:
    - "no"
  weekly_seasonality_options:
    - "exist"
  noise_levels:
    - "small"
  trend_levels:
    - "exist"
  cyclic_periods:
    - "exist"
  data_types: "additive"  # Make sure this line is correctly indented
  outliers_percentage: [0.05, 0.01, 0.03, 0.0]
  missing_percentage: [0.05, 0]
