simulation_parameters:
  start_date: 2021-07-01
  end_date: 2022-07-01
  frequencies:
    - "10T"
    - "30T"
    - "1H"
  daily_seasonality_options:
    - "no"
    - "exist"
  daily_amplitude: [0.3] 
  daily_phase_shift: [0]
  daily_multiplier: [1] 
  weekly_seasonality_options:
    - "exist"
    - "no"
  weekly_amplitude: [0.3] 
  weekly_phase_shift: [90]
  weekly_multiplier: [2]   
  noise_levels:
    - "small"
    - "large"
    - "none"
  trend_levels:
    - "exist"
    - "no"
  cyclic_periods:
    - "exist"
    - "no"
  cyclic_frequency: [0.3]  
  trend_coefficients: [0,2,1,3]  
  data_types: "additive"  # Make sure this line is correctly indented
  outliers_percentage: [0.05, 0]
  missing_percentage: [0.05, 0]

