version: '3'
services:
  flask-app:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile  # The name of your Dockerfile
    command: bash -c "python app.py"  
    ports:
      - "5000:5000"  # Expose Flask app on port 5000
    volumes:
      - ./models:/app/models  # Mount the models directory
      - ./train_lags.csv:/app/train_lags.csv  # Mount the train_lags.csv file
      - ./timestamp_intervals.csv:/app/timestamp_intervals.csv  # Mount the timestamp_intervals.csv file
