# Generated by Django 4.2.5 on 2023-09-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=10)),
                ('noise_level', models.FloatField()),
                ('trend_coefficients', models.CharField(default='0', max_length=255)),
                ('missing_percentage', models.FloatField(default=0)),
                ('outlier_percentage', models.FloatField(default=0)),
                ('cycle_component_amplitude', models.FloatField(default=1)),
                ('cycle_component_frequency', models.FloatField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Running', 'Running'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SimulatorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('time_series_type', models.CharField(choices=[('multiplicative', 'Multiplicative'), ('additive', 'Additive')], max_length=20)),
                ('meta_data', models.FileField(upload_to='system_config/')),
                ('producer_type', models.CharField(choices=[('Kafka', 'Kafka'), ('csv', 'CSV File')], max_length=20)),
                ('process_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonalityComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitude', models.FloatField()),
                ('phase_shift', models.FloatField()),
                ('frequency_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=10)),
                ('frequency_multiplier', models.FloatField()),
                ('dataset_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.datasetconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='datasetconfiguration',
            name='time_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.simulatordetail'),
        ),
        migrations.AlterUniqueTogether(
            name='datasetconfiguration',
            unique_together={('time_series', 'frequency', 'noise_level', 'trend_coefficients', 'missing_percentage', 'outlier_percentage', 'cycle_component_amplitude', 'cycle_component_frequency')},
        ),
    ]
