# Generated by Django 4.2.5 on 2023-09-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0002_alter_simulatordetail_producer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatordetail',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='submitted', max_length=10),
        ),
    ]
