# Generated by Django 4.2.7 on 2023-11-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0007_alter_simulatordetail_producer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatordetail',
            name='scheduler',
            field=models.IntegerField(default=1),
        ),
    ]
