version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: Headway
      POSTGRES_USER: youssefmedhat
      POSTGRES_PASSWORD: 12345678
    networks:
      - nifi_network
      - confluent
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Use the custom Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8085"
    volumes:
      - .:/app
      - ./Task1/sample_datasets:/csv_output
      - ./simulator_api/migrations:/app/simulator_api/migrations
    ports:
      - "8085:8085"
    depends_on:
      - db
    networks:
      - nifi_network
      - confluent

networks:
  confluent:
    external: true
  nifi_network:
    external: true