version: '3'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    environment:
      - NIFI_WEB_HTTP_HOST=localhost
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_PROXY_CONTEXT_PATH=/nifi
      - NIFI_SECURITY_USER=admin
      - NIFI_SECURITY_PASSWD=admin
    ports:
      - "8080:8080"
    volumes:
      - /mnt/d/Users/youssef.medhat/Documents/GitHub/HeadwayTasks/nifi_folder:/nifi_folder
