# system_config.yaml

data_reading:
  method: "json"  # Options: yaml, database, env, etc.
  yaml_config_file: "config.yml"  # Specify the YAML data configuration file if method is "yaml"
  database_config:
    host: "localhost"
    port: 8000
    username: "username"
    password: "password"  
    database_name: "database_name"
  env_config:
    env_var_name: "DATA_API_KEY"
# system_config.yaml

data_saving:
  producer_type: "folder"  # Specify the data saving method (folder, kafka, database, etc.)
  sink_name: "./Task1/sample_datasets/"  # Specify the folder path for saving datasets
  kafka_config:
    bootstrap_servers: ""
    sink_name: ""
  database_config:
    host: ""
    port: 8000
    database: "my_dataset_db"
    user: "my_user"
    password: "my_password"
